# Generated by Django 5.0.1 on 2024-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
