# Generated by Django 5.0.1 on 2024-03-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
