# Generated by Django 5.0.1 on 2024-03-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_assignsubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignsubscriber',
            old_name='subscriber',
            new_name='user',
        ),
    ]
