# Generated by Django 5.0.1 on 2024-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_trainer_facebook_trainer_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
