# Generated by Django 5.0.1 on 2024-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_trainermsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
