# Generated by Django 5.0.1 on 2024-03-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_subscription_price_alter_trainermsg_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
